services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "test"
    container_name: db
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5433:5433"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go
    environment:
      DB_HOST: "db"
      DB_PORT: 5432
      DB_USER: "user"
      DB_PASSWORD: "test"
      DB_NAME: "test"
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "mysecretkey123"
      MINIO_INTERNAL_ENDPOINT: "minio:9000"
      MINIO_PUBLIC_ENDPOINT: "http://localhost:9000"
    ports:
      - 8000:8000
    depends_on:
      - db

  minio:
    image: minio/minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web UI
    environment:
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "mysecretkey123"
      MINIO_ENDPOINT: "minio:9000"
    volumes:
      - minio-storage:/data
    restart: always # Авто-запуск при падении
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio-storage: